apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-deviation-service
  namespace: system
spec:
  ports:
  - name: tcp
    port: 9998
    targetPort: 9998
    protocol: TCP
  selector:
    control-plane: controller-manager