# permissions for end users to view k8ssrlnokiasystemsystemntps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssrlnokiasystemsystemntp-viewer-role
rules:
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps/status
  verbs:
  - get
