# permissions for end users to edit k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssrlnokianetworkinstancenetworkinstanceprotocolsospf-editor-role
rules:
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs/status
  verbs:
  - get
