# permissions for end users to view k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssrlnokianetworkinstancenetworkinstanceprotocolslinux-viewer-role
rules:
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxes/status
  verbs:
  - get
