# permissions for end users to edit k8ssrlnokiainterfacesinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssrlnokiainterfacesinterface-editor-role
rules:
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces/status
  verbs:
  - get
