# permissions for end users to view k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssrlnokianetworkinstancenetworkinstanceprotocolsospf-viewer-role
rules:
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs/status
  verbs:
  - get
