# permissions for end users to edit k8ssrlnokiainterfacesinterfacesubinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssrlnokiainterfacesinterfacesubinterface-editor-role
rules:
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces/status
  verbs:
  - get
