
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networkdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlbfds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlbfds/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlbfds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlinterfacesubinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlinterfacesubinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlinterfacesubinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceaggregateroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceaggregateroutes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceaggregateroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstancenexthopgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstancenexthopgroups/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstancenexthopgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgpevpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgpevpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgpevpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgpvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgpvpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsbgpvpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsises/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolslinuxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolslinuxes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolslinuxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsospfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsospfs/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstanceprotocolsospfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstances/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstancestaticroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstancestaticroutes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnetworkinstancestaticroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicyaspathsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicyaspathsets/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicyaspathsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicycommunitysets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicycommunitysets/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicycommunitysets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicypolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicyprefixsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicyprefixsets/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlroutingpolicyprefixsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemmtus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemmtus/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemmtus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnames/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsbgpvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsbgpvpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsbgpvpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpnesisbgpinstanceesis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpnesisbgpinstanceesis/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpnesisbgpinstanceesis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpnesisbgpinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpnesisbgpinstances/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpnesisbgpinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemnetworkinstanceprotocolsevpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemntps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemntps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlsystemntps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srltunnelinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srltunnelinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srltunnelinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srltunnelinterfacevxlaninterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srltunnelinterfacevxlaninterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srltunnelinterfacevxlaninterfaces/status
  verbs:
  - get
  - patch
  - update
