
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networkdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiabfdbfds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiabfdbfds/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiabfdbfds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceaggregateroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceaggregateroutes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceaggregateroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancenexthopgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancenexthopgroups/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancenexthopgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpevpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpevpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpevpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpvpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpvpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsises/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstances/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancestaticroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancestaticroutes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancestaticroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiaroutingpolicyroutingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiaroutingpolicyroutingpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiaroutingpolicyroutingpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemmtus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemmtus/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemmtus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnames/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnetworkinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnetworkinstances/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnetworkinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfacevxlaninterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfacevxlaninterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfacevxlaninterfaces/status
  verbs:
  - get
  - patch
  - update
