
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fsc.henderiw.be
  resources:
  - networknodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiainterfacesinterfacesubinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceaggregateroutess
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceaggregateroutess/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceaggregateroutess/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancenexthopgroupss
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancenexthopgroupss/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancenexthopgroupss/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpevpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpevpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpevpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpvpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpvpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsisiss
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsisiss/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsisiss/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxs/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstances/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancestaticroutess
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancestaticroutess/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokianetworkinstancenetworkinstancestaticroutess/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemmtus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemmtus/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemmtus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnames/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnetworkinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnetworkinstances/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemnetworkinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiasystemsystemntps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - k8ssrlnokiatunnelinterfacestunnelinterfaces/status
  verbs:
  - get
  - patch
  - update
