
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networkdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiabfds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiabfds/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiabfds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiainterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiainterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiainterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiainterfacesubinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiainterfacesubinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiainterfacesubinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceaggregateroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceaggregateroutes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceaggregateroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstancenexthopgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstancenexthopgroups/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstancenexthopgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgpevpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgpevpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgpevpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgpvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgpvpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsbgpvpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsises/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolslinuxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolslinuxes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolslinuxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsospfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsospfs/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstanceprotocolsospfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstances/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstancestaticroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstancestaticroutes/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokianetworkinstancestaticroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicyaspathsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicyaspathsets/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicyaspathsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicycommunitysets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicycommunitysets/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicycommunitysets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicypolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicyprefixsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicyprefixsets/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiaroutingpolicyprefixsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemmtus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemmtus/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemmtus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemnames/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemnetworkinstanceprotocolsbgpvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemnetworkinstanceprotocolsbgpvpns/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemnetworkinstanceprotocolsbgpvpns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemntps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemntps/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiasystemntps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiatunnelinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiatunnelinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiatunnelinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiatunnelinterfacevxlaninterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiatunnelinterfacevxlaninterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - srlinux.henderiw.be
  resources:
  - srlnokiatunnelinterfacevxlaninterfaces/status
  verbs:
  - get
  - patch
  - update
