apiVersion: srlinux.henderiw.be/v1alpha1
kind: SrlSystemNtp
metadata:
  name: ntp-sample
  labels:
    target: leaf1
spec:
  ntp:
    network-instance: mgmt
    admin-state: enable
    server:
      - address: 193.104.37.238
        prefer: true
      - address: 45.87.76.3
      - address: 185.111.204.220
      - address: 162.159.200.1