apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaNetworkInstanceNetworkInstanceProtocolsOspf
metadata:
  name: k8ssrlnokianetworkinstancenetworkinstanceprotocolsospf-sample
spec:
  # Add fields here
  foo: bar
