apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaInterfacesInterfaceSubinterface
metadata:
  name: subinterfacegrp2
  labels:
    target: leaf1
spec:
  interface-name: ethernet-1/2
  subinterface:
  - index: 1
    admin-state: enable
    description: "k8s-subinterface-e1.2.1"
    type: routed
    ipv4:
      address:
      - ip-prefix: 10.1.1.1/24
    ipv6:
      address:
      - ip-prefix: 2000:1::1/64
    vlan:
      encap:
        single-tagged:
          vlan-id: 1
  - index: 2
    admin-state: enable
    description: "k8s-subinterface-e1.2.2"
    type: routed
    ipv4:
      address:
      - ip-prefix: 10.2.2.1/24
    ipv6:
      address:
      - ip-prefix: 2000:2::1/64
    vlan:
      encap:
        single-tagged:
          vlan-id: 2
  - index: 3
    admin-state: enable
    description: "k8s-subinterface-e1.2.3"
    type: routed
    ipv4:
      address:
      - ip-prefix: 10.3.3.1/24
    ipv6:
      address:
      - ip-prefix: 2000:3::1/64
    vlan:
      encap:
        single-tagged:
          vlan-id: 3