
# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/srlinux.henderiw.be_srlbfds.yaml
- bases/srlinux.henderiw.be_srlinterfaces.yaml
- bases/srlinux.henderiw.be_srlinterfacesubinterfaces.yaml
- bases/srlinux.henderiw.be_srlnetworkinstances.yaml
- bases/srlinux.henderiw.be_srlnetworkinstanceaggregateroutes.yaml
- bases/srlinux.henderiw.be_srlnetworkinstancenexthopgroups.yaml
- bases/srlinux.henderiw.be_srlnetworkinstanceprotocolsbgps.yaml
- bases/srlinux.henderiw.be_srlnetworkinstanceprotocolsbgpevpns.yaml
- bases/srlinux.henderiw.be_srlnetworkinstanceprotocolsbgpvpns.yaml
- bases/srlinux.henderiw.be_srlnetworkinstanceprotocolsises.yaml
- bases/srlinux.henderiw.be_srlnetworkinstanceprotocolslinuxes.yaml
- bases/srlinux.henderiw.be_srlnetworkinstanceprotocolsospfs.yaml
- bases/srlinux.henderiw.be_srlnetworkinstancestaticroutes.yaml
- bases/srlinux.henderiw.be_srlroutingpolicyaspathsets.yaml
- bases/srlinux.henderiw.be_srlroutingpolicycommunitysets.yaml
- bases/srlinux.henderiw.be_srlroutingpolicypolicies.yaml
- bases/srlinux.henderiw.be_srlroutingpolicyprefixsets.yaml
- bases/srlinux.henderiw.be_srlsystemmtus.yaml
- bases/srlinux.henderiw.be_srlsystemnames.yaml
- bases/srlinux.henderiw.be_srlsystemnetworkinstanceprotocolsbgpvpns.yaml
- bases/srlinux.henderiw.be_srlsystemnetworkinstanceprotocolsevpns.yaml
- bases/srlinux.henderiw.be_srlsystemnetworkinstanceprotocolsevpnesisbgpinstances.yaml
- bases/srlinux.henderiw.be_srlsystemnetworkinstanceprotocolsevpnesisbgpinstanceesis.yaml
- bases/srlinux.henderiw.be_srlsystemntps.yaml
- bases/srlinux.henderiw.be_srltunnelinterfaces.yaml
- bases/srlinux.henderiw.be_srltunnelinterfacevxlaninterfaces.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_k8ssrlnokiainterfacesinterfaces.yaml
#- patches/webhook_in_k8ssrlnokiainterfacesinterfacesubinterfaces.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemntps.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemnames.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemmtus.yaml
#- patches/webhook_in_k8ssrlnokianetworkinstances.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_k8ssrlnokiainterfacesinterfaces.yaml
#- patches/cainjection_in_k8ssrlnokiainterfacesinterfacesubinterfaces.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemntps.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemnames.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemmtus.yaml
#- patches/cainjection_in_k8ssrlnokianetworkinstances.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
