
# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/srlinux.henderiw.be_srlnokiabfds.yaml
- bases/srlinux.henderiw.be_srlnokiainterfaces.yaml
- bases/srlinux.henderiw.be_srlnokiainterfacesubinterfaces.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstances.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstanceaggregateroutes.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstancenexthopgroups.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstanceprotocolsbgps.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstanceprotocolsbgpevpns.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstanceprotocolsbgpvpns.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstanceprotocolsises.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstanceprotocolslinuxes.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstanceprotocolsospfs.yaml
- bases/srlinux.henderiw.be_srlnokianetworkinstancestaticroutes.yaml
- bases/srlinux.henderiw.be_srlnokiaroutingpolicyaspathsets.yaml
- bases/srlinux.henderiw.be_srlnokiaroutingpolicycommunitysets.yaml
- bases/srlinux.henderiw.be_srlnokiaroutingpolicypolicies.yaml
- bases/srlinux.henderiw.be_srlnokiaroutingpolicyprefixsets.yaml
- bases/srlinux.henderiw.be_srlnokiasystemmtus.yaml
- bases/srlinux.henderiw.be_srlnokiasystemnames.yaml
- bases/srlinux.henderiw.be_srlnokiasystemnetworkinstanceprotocolsbgpvpns.yaml
- bases/srlinux.henderiw.be_srlnokiasystemntps.yaml
- bases/srlinux.henderiw.be_srlnokiatunnelinterfaces.yaml
- bases/srlinux.henderiw.be_srlnokiatunnelinterfacevxlaninterfaces.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_k8ssrlnokiainterfacesinterfaces.yaml
#- patches/webhook_in_k8ssrlnokiainterfacesinterfacesubinterfaces.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemntps.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemnames.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemmtus.yaml
#- patches/webhook_in_k8ssrlnokianetworkinstances.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_k8ssrlnokiainterfacesinterfaces.yaml
#- patches/cainjection_in_k8ssrlnokiainterfacesinterfacesubinterfaces.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemntps.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemnames.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemmtus.yaml
#- patches/cainjection_in_k8ssrlnokianetworkinstances.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
