# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/srlinux.henderiw.be_k8ssrlnokiainterfacesinterfaces.yaml
- bases/srlinux.henderiw.be_k8ssrlnokiainterfacesinterfacesubinterfaces.yaml
- bases/srlinux.henderiw.be_k8ssrlnokiasystemsystemntps.yaml
- bases/srlinux.henderiw.be_k8ssrlnokiasystemsystemnames.yaml
- bases/srlinux.henderiw.be_k8ssrlnokiasystemsystemmtus.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstanceaggregateroutes.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstancenexthopgroups.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgps.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstanceprotocolsises.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstanceprotocolslinuxes.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstanceprotocolsospfs.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstances.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstancestaticroutes.yaml
- bases/srlinux.henderiw.be_k8ssrlnokiatunnelinterfacestunnelinterfaces.yaml
- bases/srlinux.henderiw.be_k8ssrlnokiasystemsystemnetworkinstances.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpevpns.yaml
- bases/srlinux.henderiw.be_k8ssrlnokianetworkinstancenetworkinstanceprotocolsbgpvpns.yaml

# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_k8ssrlnokiainterfacesinterfaces.yaml
#- patches/webhook_in_k8ssrlnokiainterfacesinterfacesubinterfaces.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemntps.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemnames.yaml
#- patches/webhook_in_k8ssrlnokiasystemsystemmtus.yaml
#- patches/webhook_in_k8ssrlnokianetworkinstances.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_k8ssrlnokiainterfacesinterfaces.yaml
#- patches/cainjection_in_k8ssrlnokiainterfacesinterfacesubinterfaces.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemntps.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemnames.yaml
#- patches/cainjection_in_k8ssrlnokiasystemsystemmtus.yaml
#- patches/cainjection_in_k8ssrlnokianetworkinstances.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
